name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Build APK
        uses: flet-dev/build-flet-apk-action@v1
        with:
          path: app.py
          project_name: "CyberAggregator"
          package_name: "com.cyber.aggregator"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Cyber-Aggregator-App
          path: build/apk/*.apk
